apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.111.0
          args:
            - "--config=/etc/otel-collector-config.yaml"
          ports:
            - containerPort: 4317  # OTLP gRPC
            - containerPort: 9464  # Prometheus metrics exposed here
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: opentelemetry
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              static_configs:
                - targets: ['0.0.0.0:8888']

    exporters:
      otlp/jaeger:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:9464"
        namespace: "otel_collector"
      debug: {} # <--- ADDED THIS LINE: Defines the debug exporter

    processors:
      batch: {}

    connectors:
      spanmetrics:
        namespace: span.metrics

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug] # This now correctly references the defined debug exporter
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp/jaeger, spanmetrics] # This now correctly references the defined debug exporter
        metrics:
          receivers: [prometheus, otlp, spanmetrics]
          processors: [batch]
          exporters: [debug, prometheus] # This now correctly references the defined debug exporter

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: otlp-grpc
    - protocol: TCP
      port: 9464
      targetPort: 9464
      name: prometheus
  type: NodePort