---
- name: Apply Prometheus configuration and start service in Minikube
  hosts: all
  #become: yes  # Optional, if sudo permissions are required
  tasks:
    - name: Apply Prometheus configuration
      command: kubectl apply -f prometheus.yaml
      args:
        chdir: ./  # Adjust path as needed
