apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.111.0
          args:
            - "--config=/etc/otel-collector-config.yaml"
          ports:
            - containerPort: 4317
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml  # Mount the config as a file
              subPath: config.yaml  # This points to the correct key in the ConfigMap
      volumes:
        - name: otel-config
          configMap:
            name: otel-config  # Reference the ConfigMap containing the configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: opentelemetry
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      otlp/jaeger:
        endpoint: "jaeger:4317"  # Update to use the correct Jaeger endpoint
        tls:
          insecure: true
      debug: {}  # Use debug exporter instead of logging

    processors:
      batch: {}

    service:
        pipelines:
            logs:
                receivers: [otlp]
                processors: [batch]
                exporters: [debug]
            traces: 
                receivers: [otlp]
                processors: [batch]
                exporters: [debug, otlp/jaeger]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
  type: NodePort
