---
- name: Install Minikube with Podman on macOS and Linux
  hosts: all
  tasks:
    - name: Install dependencies on Debian/Ubuntu
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - conntrack
        state: present
      become: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies on macOS
      homebrew:
        name:
          - curl
        state: present
      when: ansible_os_family == "Darwin"

    - name: Install Podman on Debian/Ubuntu
      apt:
        name: podman
        state: present
      become: yes
      when: ansible_os_family == "Debian"

    - name: Install Podman on macOS
      homebrew:
        name: podman
        state: present
      when: ansible_os_family == "Darwin"

    - name: Download Minikube binary for macOS
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
        validate_certs: no
      become: yes
      when: ansible_os_family == "Darwin"

    - name: Download Minikube binary for Linux
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
      become: yes
      when: ansible_os_family == "Debian"

    - name: Start Minikube with Podman
      command: minikube start --driver=podman
      register: minikube_start
      changed_when: "'Done' in minikube_start.stdout"
      ignore_errors: yes

    - name: Display Minikube start status
      debug:
        var: minikube_start.stdout
